var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var currencySchema = new Schema({
  "currencyId"  : { type: mongoose.Schema.Types.ObjectId, index: true, ref: 'CurrencySymbol'},
  "currencyName": {type: String, index: true},
  "currencySymbol": {type: String, index: true},
  "currencySymbolCode": {type: String, index: true},
  "depositEnable": { type: Number, default: 0 },
  "withdrawLevel": { type: Object, default: {level1:{fees:0,feetype:1,minwithamt:0},level2:{fees:0,feetype:1,minwithamt:0},level2:{fees:0,feetype:1,minwithamt:0}} },
  "autoWithdraw": { type: Number, default: 0 },
  "USDvalue": { type: Number, default: 0 },
  "INRvalue": { type: Number, default: 1 },
  "BTCvalue": { type: Number, default: 0 },
  "ETHvalue": { type: Number, default: 0 },
  "status": { type: Number, default: 1 },
  "basecoin": { type: String, default: '' },
  "contractAddress": { type: String, default: '' },
  "decimal": { type: Number, default: 0 },
  "apiid": { type: String, default: '' },
  "tradeEnable": { type: Number, default: 0 },
  "withdrawEnable": { type: Number, default: 0 },
  "curnType": { type: String, default: "Crypto" },
  "depositNotes": { type: String, default: "Crypto" },
  "withdrawNotes": { type: String, default: "Crypto" },
  "image": { type: String, default: "" },
  "tagContent": { type: String, default: "" },
  "siteDecimal": { type: Number, default: 8 },
  "cointype": { type: Number, default: 0 },
  "transferEnable": { type: Number, default: 0 },
  "perpetualTransferEnable": { type: Number, default: 0 },
  "stakingTransferEnable": { type: Number, default: 0 },
  "minCurDeposit": { type: Number, default: 0 },
  "minWalletTransfer": { type: Number, default: 0 },
});
module.exports = mongoose.model('Currency', currencySchema, 'Currency');