var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var siteSettingsSchema = new Schema({
	"siteName"   : {type:String},
	"adminSiteName"   : {type:String},
	"siteLogo"   : {type:String},
	"favIcon"   : {type:String},
	"copyRights"   : {type:String, default: ''},
	"tradeText"   : {type:String, default: ''},
	"supportEmail"   : {type:String, default: ''},
	"stakingEmail"   : {type:String, default: ''},
	"address"   : {type:String, default: ''},
	"facebookLink"   : {type:String},
	"telegramLink"   : {type:String},
	"twitterLink"   : {type:String},
	"mediumLink"   : {type:String},
	"instagramLink"   : {type:String},
	"youtubeLink"   : {type:String},
	"linkedinLink"   : {type:String},
	"pinterestLink"   : {type:String},
	"socialIcons"   : {type:Object,default:{}},
	"linkExpireTiming":{type:Number},
	"minDeposit":{type:Number, default: 0},
	"withdrawLevel": { type: Object, default: {level1:{dailyVolume:0,monthlyVolume:0,tradeMaxLimit:0},level2:{dailyVolume:0,monthlyVolume:0},level3:{dailyVolume:0,monthlyVolume:0}} },
	"stakingLevel": { type: Object, default: {level1:{walletDailyVolume:0,walletMonthlyVolume:0,stakingDailyVolume:0,stakingMonthlyVolume:0},level2:{walletDailyVolume:0,walletMonthlyVolume:0,stakingDailyVolume:0,stakingMonthlyVolume:0},level3:{walletDailyVolume:0,walletMonthlyVolume:0,stakingDailyVolume:0,stakingMonthlyVolume:0}} },
	"referralCommission":{type:Number, default: 0},
	"referralBonusStatus":{type:Number, default: 0},
	"registerBonusDate":{type:String, default: ''},
	"referralBonus":{type:Number, default: 0},
	"registerBonusStatus":{type:Number, default: 0},
	"registerBonus":{type:Number, default: 0},
    "referralBonusCurrency"  : { type: mongoose.Schema.Types.ObjectId, ref: 'Currency'},
	"maintenanceContent":{type:String, default: ''},
	"maintenanceFinishTime":{type:String, default: ''},
	"appmaintenanceContent":{type:String, default: ''},
	"appmaintenanceFinishTime":{type:String, default: ''},
	"stakingreferralBonus": { type:Number , default:0},
	"paymentGatewayFees":{type:Number, default: 0},
	"applicationBonuscurr":{ type: mongoose.Schema.Types.ObjectId, ref: 'Currency'},
	"applicationBonus": { type:Number , default:0},
	"applicationBonusEndDate":{type:String, default: ''},
	"preBookingStatus":{type:Number, default: 0},
	"bonusExpiredPeriod":{type:Number, default: 0},
	"preBookingTime":{type:String, default: '10-12'},
	"preBookingContent":{type:String, default: 'Next pre booking time is 30 June 2022, 2 PM to 4 PM'},
	"preBookingPercentage" : [{
		from : String,
		to : String,
		bonus : String
	}],	
	"tradeFeeDiscount": { type: Number, default: 50 },
	"tradeFeeDiscountCurrency": { type: mongoose.Schema.Types.ObjectId, ref: 'Currency'},
	"tradeUSDTValue": { type: Number, default: 1 },
	"tradeUSDTType": { type: String, default: '+' },
	"tradeTDSPercentage": { type: Number, default: 1 },
	"extraBonusDate": { type: String, default: '22-07-2022' },
	"extraBonus": { type: Number, default: 5 },
	"userMaxTradeCount": { type: Number, default: 10 }
});
module.exports = mongoose.model('SiteSettings', siteSettingsSchema, 'SiteSettings')