module.exports = {
    USER_SCCESSFULL: "User active form created successful!",
    ALREADY_USER: "User is already register",
    NEW_REFERRAL: "Referral account is created successful!",
    USER_NOT_FOUND : "User is not found",
    ALREADY_LAUNCHPAD_REJECT: "This user Launchpad token is already rejected",
    ALREADY_LAUNCHPAD_APPROVE: "This user Launchpad token is already approved",
    USER_UPDATE_SCCESSFULL: "User updated successful!",
    COIN_CREATE_SUCCESSFULL: "Coin created successful!",
    ALREADY_COIN: "Coin is already created",
    COIN_CONFIG_CREATE: "Coin config created successful!",
    LOAN_CONFIG_CREATE: "Loan config created successful!",
    COLLATERAL_CONFIG_CREATE: "Collateral config created successful!",
    COIN_ERROR: "Please select the coin",
    ALREADY_COIN_SELECTED: "Already this coin is selected!",
    COLLATERAL_NOT_FOUND: "Collateral is not found",
    COLLATERAL_UPDATE_SUCCESS: "Collateral config updated successful!",
    LOAN_NOT_FOUND: "Loan is not found",
    LOAN_UPDATE_SUCCESS: "Loan config updated successful!",
    CRYPTO_LOAN_UPDATED: "Crypto loan updated successful!",
    CRYPTO_LOAN_NOT_FOUND: "Crypto loan is not found",
    REPAYMENT_SUCCESS: "Crypto loan repaid successful!",
    ALREADY_LOAN_ACCURED: "Already You borrow loan accruing repaid",
    SET_TIME_INTERVAL: "Please wait for 5 seconds before placing another request!",
}